os: linux
language: shell

services:
  - docker
  - mysql

before_script:
  - docker-compose run themebuilder npm --prefix app/themes/bulma install
  - docker-compose run themebuilder npm --prefix app/themes/bulma build

script:
  - docker-compose run -e "SS_BASE_URL=//matthew.cle.gg" cli make deploy

before_deploy:
  - find themes/bulma/*/ -type d -name "node_modules" -prune -o -type f \( -iname \*.css -o -iname \*.jpg -o -iname \*.js \) -exec cp --parents \{\} ./cache \;

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: cache
  strategy: git