os: linux
language: shell

services:
  - docker
  - mysql

before_script:
  - make npm-run-build

script:
  - docker run -it -v $PWD:/app -w /app
    -e "SS_DATABASE_CHOOSE_NAME=1"
    -e "SS_BASE_URL=//matthew.cle.gg"
    -e "SS_DATABASE_SERVER=`ip r | awk '/default/{print $3}'`"
    silverstripecloud/composer:latest
    make deploy

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: cache
  strategy: git